### ISSUE TITLE
Compile error: #error "This version of GLEQ only supports GLFW 3"

### ISSUE THREAD

**Issue by sparkecho** [glfw/gleq#4]
When I use the following compile command this error would appear. `g++ gleq.h test.c -lglfw` 
The version of `GLFW` I installed is `3.2`. After adding `#include <GLFW/glfw3.h>` in `gleq.h` the error disappears. 
I do not know if this is a bug or my compile method is not correct. If the reason is the latter one, add a `Makefile` would be very good. Thanks.

**Comment by elmindreda** [comment]
Yup, the GLEQ header didn't support being compiled on its own, but that could be useful. This has been fixed with efb4b4b4aa6bf775b15ae9357161c5895ebefbe7. Thank you!

Note that `GLEQ_IMPLEMENTATION` needs to be defined for the header to produce anything during compilation. The `test.c` file does this already, so there is no need to compile `gleq.h` separately.
